# Generated by Django 2.0.8 on 2019-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='hybridopedia'),
        ),
    ]
