# Generated by Django 2.0.8 on 2019-12-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hybridopedia', '0003_subject_author'),
        ('registration', '0021_subject_datamigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
