# Generated by Django 2.0.8 on 2020-02-12 16:55

import apps.hybridopedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hybridopedia', '0004_auto_20191206_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=apps.hybridopedia.models.File.get_path),
        ),
    ]
