# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161030_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
