# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20161011_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_waiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
