# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161223_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
    ]
