# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161018_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
