# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20161230_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='news',
            field=models.BooleanField(default=True),
        ),
    ]
