# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_event_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genders',
            field=models.CharField(default='MFU', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='grades',
            field=models.CharField(default='12345', max_length=5),
        ),
        migrations.AddField(
            model_name='event',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, related_name='waiting', to=settings.AUTH_USER_MODEL),
        ),
    ]
