# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170202_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
