# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_auto_20161018_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_waiting',
        ),
    ]
