# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_max_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
