# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ingress',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
