# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_remove_attendancefields_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='excursion',
            field=models.BooleanField(default=False),
        ),
    ]
