# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0012_add_timestamp_ordering_participation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_id', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
