# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 12:52
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_tpevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
