# Generated by Django 2.0.8 on 2019-03-06 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20190130_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markpunishment',
            name='duration',
        ),
        migrations.AddField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 16, 54, 19, 660301)),
        ),
    ]
