# Generated by Django 2.0.8 on 2018-10-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_auto_20181009_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='_attendance_participants_+', through='events.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationsecondary',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Attendance'),
        ),
        migrations.AddField(
            model_name='participationsecondary',
            name='hybrid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='participantsSecondary',
            field=models.ManyToManyField(blank=True, related_name='_attendance_participantsSecondary_+', through='events.ParticipationSecondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participationsecondary',
            unique_together={('hybrid', 'attendance')},
        ),
    ]
