# Generated by Django 2.0.8 on 2019-03-06 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190306_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.date(2019, 7, 1)),
        ),
    ]
