# Generated by Django 2.0.8 on 2018-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20181021_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['marks'],
            },
        ),
        migrations.CreateModel(
            name='MarkPunishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goes_on_secondary', models.PositiveIntegerField(default=0)),
                ('too_many_marks', models.PositiveIntegerField(default=0)),
                ('delays', models.ManyToManyField(blank=True, to='events.Delays')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='delays',
            unique_together={('marks', 'minutes')},
        ),
    ]
