# Generated by Django 2.0.8 on 2019-03-06 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190306_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 17, 7, 13, 889473)),
        ),
    ]
