# Generated by Django 2.0.8 on 2018-11-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181102_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delays',
            new_name='Delay',
        ),
        migrations.RenameField(
            model_name='markpunishment',
            old_name='delays',
            new_name='delay',
        ),
    ]
