# Generated by Django 2.0.8 on 2019-03-13 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190306_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='markpunishment',
            name='signoff_close',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 13, 45, 39, 461840)),
        ),
    ]
