# Generated by Django 2.0.8 on 2018-11-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20181103_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='punishment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.MarkPunishment'),
        ),
    ]
