# Generated by Django 2.0.8 on 2018-11-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_delay_punishment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delay',
            options={'ordering': ['-marks']},
        ),
    ]
