# Generated by Django 2.0.8 on 2018-11-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20181105_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='markpunishment',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
