# Generated by Django 2.0.8 on 2018-11-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_markpunishment_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
