# Generated by Django 2.0.8 on 2018-11-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20181112_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, default='', max_length=500)),
                ('punishment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.MarkPunishment')),
            ],
        ),
        migrations.AddField(
            model_name='markpunishment',
            name='rules',
            field=models.ManyToManyField(blank=True, to='events.Rule'),
        ),
    ]
