# Generated by Django 2.0.8 on 2019-03-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20190313_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 0, 0)),
        ),
    ]
