# Generated by Django 2.0.8 on 2019-09-13 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20190313_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signoff_close',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
