# Generated by Django 2.0.8 on 2019-09-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20190913_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signoff_close',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='markpunishment',
            name='signoff_close',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
