# Generated by Django 2.0.8 on 2019-09-18 15:39

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20190913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateTimeField(default=apps.events.models.mark_end_default),
        ),
    ]
