# Generated by Django 2.0.8 on 2019-09-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20190918_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signoff_close',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='markpunishment',
            name='signoff_close',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
