# Generated by Django 2.0.8 on 2019-10-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20190919_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay',
            name='punishment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_delays', to='events.MarkPunishment'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='punishment',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_rules', to='events.MarkPunishment'),
        ),
    ]
