# Generated by Django 2.0.8 on 2019-10-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20191014_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signoff_close_on_signup_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markpunishment',
            name='mark_on_late_signoff',
            field=models.BooleanField(default=True),
        ),
    ]
