# Generated by Django 2.0.8 on 2019-11-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20191025_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('use_delay', models.BooleanField(default=False)),
                ('use_goes_on_secondary', models.BooleanField(default=False)),
                ('use_too_many_marks', models.BooleanField(default=False)),
                ('use_mark_on_late_signoff', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventType'),
        ),
    ]
