# Generated by Django 2.0.8 on 2020-01-02 16:01

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20191119_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='end',
            field=models.DateField(default=apps.events.models.end_of_semester),
        ),
    ]
