# Generated by Django 2.0.8 on 2019-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20191119_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='use_remove_on_too_many_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markpunishment',
            name='remove_on_too_many_marks',
            field=models.BooleanField(default=True),
        ),
    ]
