# Generated by Django 2.0.8 on 2020-01-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20191228_1410'),
        ('events', '0035_auto_20200102_1701'),
    ]

    operations = [
    ]
