# Generated by Django 2.0.8 on 2020-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('events', '0036_merge_20200102_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
