# Generated by Django 2.0.8 on 2020-01-30 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_attendance_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='hybridattendances', through='events.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participantsSecondary',
            field=models.ManyToManyField(blank=True, related_name='hybridattendances_secondary', through='events.ParticipationSecondary', to=settings.AUTH_USER_MODEL),
        ),
    ]
