# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='graduation_year',
            field=models.IntegerField(default=apps.accounts.models.five_years),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
