# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161019_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='specialization',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
