# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hybrid_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hybrid',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
