# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161027_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
