# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20171007_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.FileField(upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_placeholder',
            field=models.FileField(upload_to='badges/'),
        ),
    ]
