# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('griffensorden', '0001_initial'),
        ('achievements', '0003_auto_20171017_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=0)),
                ('commite_member', models.BooleanField(default=0)),
                ('hyb_member', models.BooleanField(default=0)),
                ('jub_medal', models.BooleanField(default=0)),
                ('vago', models.BooleanField(default=0)),
                ('simsim', models.BooleanField(default=0)),
                ('participation_badge', models.BooleanField(default=0)),
                ('quiz_winner', models.BooleanField(default=0)),
                ('ridder', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='griffensorden.Ridder')),
            ],
        ),
    ]
