# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='prereq',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='achievements.Prerequisites'),
        ),
    ]
