# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_badge_prereq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisites',
            name='ridder',
            field=models.BooleanField(default=0),
        ),
    ]
