# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_auto_20171018_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisites',
            name='council_medal',
            field=models.BooleanField(default=False),
        ),
    ]
