# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_prerequisites_council_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisites',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='badge',
            name='scorepoints',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prerequisites',
            name='years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
