# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_auto_20171020_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='prereq',
        ),
        migrations.DeleteModel(
            name='Prerequisites',
        ),
    ]
