# Generated by Django 2.0.2 on 2018-02-18 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_remove_badge_badge_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.ImageField(upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='hybrider', to=settings.AUTH_USER_MODEL),
        ),
    ]
