# Generated by Django 2.0.4 on 2018-05-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0015_auto_20180503_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeforslag',
            name='profil',
        ),
    ]
