# Generated by Django 2.0.8 on 2019-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0017_auto_20190215_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgerequest',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='badgerequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1),
        ),
    ]
