# Generated by Django 2.0.8 on 2019-03-06 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0018_auto_20190217_2054'),
    ]

    operations = [
        migrations.RenameModel('BadgeForslag', 'BadgeSuggestion'),
        migrations.RenameField(
            model_name='badgesuggestion',
            old_name='tildeles',
            new_name='award_to',
        ),
        migrations.RenameField(
            model_name='badgesuggestion',
            old_name='beskrivelse',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='badgesuggestion',
            old_name='badge_bilde',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='badgesuggestion',
            old_name='navn',
            new_name='name',
        ),
        migrations.AddField(
            model_name='badgesuggestion',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
