# Generated by Django 2.0.2 on 2018-03-06 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commite_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_on_list', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='referat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('people', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
    ]
