# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('rfid', '0001_initial'), ('rfid', '0002_auto_20171002_1714')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_participation_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearances',
            fields=[
                ('event',
                 models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='events.Event')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
