# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
