# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-16 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20170316_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardreport',
            name='report',
            field=models.FileField(upload_to='pdf/møtereferat'),
        ),
    ]
