# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-21 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0003_auto_20170316_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardreport',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='report',
            field=models.FileField(upload_to='pdf/referat'),
        ),
    ]
