# Generated by Django 2.0.3 on 2018-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
