# Generated by Django 2.0.3 on 2018-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0007_auto_20180407_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='description',
            new_name='beskrivelse',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='navn',
        ),
    ]
