# Generated by Django 2.0.3 on 2018-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0008_auto_20180407_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=500)),
                ('commitee', models.CharField(choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen')], max_length=500)),
            ],
        ),
    ]
