# Generated by Django 2.0.3 on 2018-04-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0009_comapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comapplication',
            old_name='commitee',
            new_name='komite',
        ),
    ]
