# Generated by Django 2.0.4 on 2018-04-24 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0010_auto_20180418_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comapplication',
            old_name='komite',
            new_name='prioritet_1',
        ),
        migrations.AddField(
            model_name='comapplication',
            name='prioritet_2',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen')], max_length=500),
        ),
        migrations.AddField(
            model_name='comapplication',
            name='prioritet_3',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen')], max_length=500),
        ),
        migrations.AddField(
            model_name='comapplication',
            name='prioritet_4',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen')], max_length=500),
        ),
        migrations.AlterField(
            model_name='comapplication',
            name='navn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
