# Generated by Django 2.0.4 on 2018-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0011_auto_20180424_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='comapplication',
            name='kommentar',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
