# Generated by Django 2.0.4 on 2018-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0012_comapplication_kommentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comapplication',
            name='prioritet_1',
            field=models.CharField(choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen'), ('Prokom', 'Prokom')], max_length=500),
        ),
        migrations.AlterField(
            model_name='comapplication',
            name='prioritet_2',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen'), ('Prokom', 'Prokom')], max_length=500),
        ),
        migrations.AlterField(
            model_name='comapplication',
            name='prioritet_3',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen'), ('Prokom', 'Prokom')], max_length=500),
        ),
        migrations.AlterField(
            model_name='comapplication',
            name='prioritet_4',
            field=models.CharField(blank=True, choices=[('Vevkom', 'Vevkom'), ('Bedkom', 'Bedkom'), ('Arrkom', 'Arrkom'), ('Jentekom', 'Jentekom'), ('Kjellerkom', 'Kjellerkom'), ('Redaksjonen', 'Redaksjonen'), ('Prokom', 'Prokom')], max_length=500),
        ),
    ]
