# Generated by Django 2.0.8 on 2018-10-16 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0015_auto_20180831_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITVreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='pdf/ITVreferat')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
