# Generated by Django 2.0.8 on 2018-10-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0016_itvreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITVreport',
            new_name='ITV_report',
        ),
    ]
