# Generated by Django 2.0.8 on 2018-10-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0017_auto_20181016_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITV_report',
            new_name='Ktv_report',
        ),
    ]
