# Generated by Django 2.0.8 on 2019-12-23 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0020_auto_20181023_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute', models.FileField(upload_to='pdf/statutter', verbose_name='Statutter')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Dato (Format: ÅÅÅÅ-MM-DD)')),
            ],
        ),
    ]
