# Generated by Django 2.0.8 on 2019-12-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0021_statute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updatek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontpage', models.FileField(upload_to='pdf/updatek', verbose_name='Forsidebilde')),
                ('pdf', models.FileField(upload_to='pdf/updatek')),
                ('school_year', models.CharField(blank=True, max_length=50,
                                                 verbose_name='Skoleår (Eks: 2018-2019 eller 2019-2020)')),
                ('edition', models.IntegerField(verbose_name='Utgave nummer')),
            ],
        ),
    ]
