# Generated by Django 2.0.8 on 2020-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0022_updatek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='beskrivelse',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='navn',
            new_name='name',
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=500, verbose_name='navn'),
        ),
    ]
