# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 07:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Booket', 'BOOKET'), ('Kontaktet', 'KONTAKTET'), ('Takket nei', 'NEI')], max_length=15)),
                ('priority', models.CharField(choices=[('Høy', 'HØY'), ('Middels', 'MIDDELS'), ('Lav', 'LAV')], max_length=10, null=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedkom.Company')),
            ],
        ),
    ]
