# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bedkom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycomment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedkom.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
