# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161030_1740'),
        ('bedkom', '0002_auto_20161030_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
