# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0004_auto_20161229_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='placeholder-logo.png', upload_to='companies'),
        ),
    ]
