# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0004_earlierbedpresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlierbedpresses',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
