# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0005_earlierbedpresses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlierbedpresses',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bedkom.Company'),
            preserve_default=False,
        ),
    ]
