# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0005_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycomment',
            old_name='commenter',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='companycomment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
