# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0006_auto_20170107_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='telephone',
        ),
    ]
