# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0009_auto_20170124_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
    ]
