# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bedkom', '0010_auto_20170206_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedpress',
            options={'verbose_name': 'Bedriftspresentasjon', 'verbose_name_plural': 'Bedriftspresentasjoner'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Bedrift', 'verbose_name_plural': 'Bedrifter'},
        ),
        migrations.AlterModelOptions(
            name='contact_person',
            options={'verbose_name': 'Kontaktperson', 'verbose_name_plural': 'Kontaktpersoner'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(
                choices=[('Booket', 'BOOKET'), ('Opprettet kontakt', 'KONTAKTET'), ('Takket nei', 'NEI'),
                         ('Ikke kontaktet', 'IKKE_KONTAKTET'), ('Sendt mail', 'SENDT_MAIL')], max_length=20),
        ),
    ]
