# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bedkom', '0011_auto_20170209_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kontaktperson', 'verbose_name_plural': 'Kontaktpersoner'},
        ),
        migrations.AlterModelOptions(
            name='contact_person',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact_person',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bedkom.Contact_person'),
        ),
    ]
