# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bedkom', '0012_auto_20170301_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Bedrift', 'verbose_name_plural': 'Bedrifter'},
        ),
        migrations.AlterModelOptions(
            name='contact_person',
            options={'verbose_name': 'Kontaktperson', 'verbose_name_plural': 'Kontaktpersoner'},
        ),
    ]
