# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0013_auto_20170307_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_person',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_person',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
