# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0014_auto_20170322_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Booket', 'BOOKET'), ('Opprettet kontakt', 'KONTAKTET'), ('Takket nei', 'NEI'), ('Ikke kontaktet', 'IKKE_KONTAKTET')], max_length=20),
        ),
    ]
