# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0015_auto_20170328_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('Høy', 'Høy'), ('Middels', 'Middels'), ('Lav', 'Lav')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Booket', 'Booket'), ('Opprettet kontakt', 'Opprettet kontakt'), ('Takket nei', 'Takket nei'), ('Ikke kontaktet', 'Ikke kontaktet')], max_length=20),
        ),
    ]
