# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0017_auto_20170905_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
