# Generated by Django 2.0.8 on 2018-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_hybrid_accepted_conditions'),
        ('bedkom', '0022_company_relevant_spesializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='relevant_spesializations',
        ),
        migrations.AddField(
            model_name='company',
            name='relevant_spesializations',
            field=models.ManyToManyField(blank=True, null=True, to='registration.Specialization'),
        ),
    ]
