# Generated by Django 2.0.8 on 2018-10-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedkom', '0023_auto_20181002_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='relevant_spesializations',
            field=models.ManyToManyField(blank=True, to='registration.Specialization'),
        ),
    ]
