# Generated by Django 2.0.8 on 2018-09-18 18:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('kiltshop', '0001_initial'), ('kiltshop', '0002_order_user'), ('kiltshop', '0003_auto_20161102_1629'),
                ('kiltshop', '0004_auto_20161102_1640'), ('kiltshop', '0005_auto_20161102_1643'),
                ('kiltshop', '0006_auto_20161102_2134'), ('kiltshop', '0007_auto_20161103_1518'),
                ('kiltshop', '0008_auto_20161103_1521'), ('kiltshop', '0009_auto_20161106_1729'),
                ('kiltshop', '0010_order_status'), ('kiltshop', '0011_auto_20161108_1915'),
                ('kiltshop', '0012_auto_20161108_2108'), ('kiltshop', '0013_auto_20170103_0124'),
                ('kiltshop', '0014_auto_20170105_1650'), ('kiltshop', '0015_remove_orderinfo_status')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='placeholder-event.png', upload_to='products')),
                ('type', models.CharField(choices=[('K', 'Kilt'), ('S', 'Sporran'), ('E', 'Ekstra')], default='K',
                                          max_length=1)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(default=663, on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sizes', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('kiltshop_start', models.DateTimeField(blank=True, null=True)),
                ('kiltshop_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order_list',
            name='orders',
            field=models.ManyToManyField(to='kiltshop.Order'),
        ),
        migrations.RenameModel(
            old_name='order_list',
            new_name='Kiltshop',
        ),
        migrations.RemoveField(
            model_name='kiltshop',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Kiltshop',
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=64, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiltshop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiltshop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='kiltshop.ProductInfo', to='kiltshop.Product'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='orders',
            field=models.ManyToManyField(blank=True, to='kiltshop.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='status',
        ),
    ]
