# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('K', 'Kilt'), ('S', 'Sporran'), ('E', 'Ekstra')], default='K', max_length=1),
        ),
    ]
