# Generated by Django 2.0.8 on 2019-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('kiltshop', '0002_auto_20181030_2111'),
    ]

    operations = [
        migrations.RenameModel('OrderInfo', 'OrderPeriod'),
        migrations.AlterField(
            model_name='orderperiod',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='period', to='kiltshop.Order'),
        ),
    ]
