# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0003_auto_20161102_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_list',
            new_name='Overview',
        ),
    ]
