# Generated by Django 2.0.8 on 2019-11-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0004_move_order_period_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderperiod',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='orderperiod',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
