# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0005_auto_20161102_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiltshop',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Kiltshop',
        ),
    ]
