# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0008_auto_20161103_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='members',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='kiltshop.ProductInfo', to='kiltshop.Product'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='orders',
            field=models.ManyToManyField(to='kiltshop.Order'),
        ),
    ]
