# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0009_auto_20161106_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
