# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiltshop', '0010_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='orders',
            field=models.ManyToManyField(blank=True, to='kiltshop.Order'),
        ),
    ]
