# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='placeholder-event.png', upload_to='quiz'),
        ),
    ]
