# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bedkom', '0003_bedpress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('descripion', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('logo', models.ImageField(default='placeholder-event.png', upload_to='events')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedkom.Company')),
            ],
        ),
    ]
