# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobannouncements', '0002_auto_20161228_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
    ]
