# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobannouncements', '0003_remove_job_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.BooleanField(default=0),
        ),
    ]
