# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobannouncements', '0004_auto_20170109_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
