# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 12:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobannouncements', '0006_auto_20170308_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
