# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 12:45
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobannouncements', '0007_job_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='test',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
