# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_add_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabToken',
            fields=[
                ('hybrid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gitlab_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=50, verbose_name='Private Token')),
            ],
        ),
    ]
