# Generated by Django 2.0.2 on 2018-02-06 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabtoken',
            name='hybrid',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gitlab_token', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
