# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hybrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('member', models.BooleanField(default=False)),
                ('graduation_year', models.IntegerField(default=apps.registration.models.five_years)),
                ('image',
                 models.ImageField(default='placeholder-profile.jpg', upload_to=apps.registration.models.user_folder)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('specialization', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
