# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='specialization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
