# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def create_empty_specialization(apps, schema_editor):
    apps.get_model('registration', 'Specialization').objects.get_or_create(name='')


def copy_specialization(apps, schema_editor):
    Hybrid = apps.get_model('registration', 'Hybrid')
    Specialization = apps.get_model('registration', 'Specialization')
    for hybrid in Hybrid.objects.all().order_by('specialization'):
        spec, created = Specialization.objects.get_or_create(name=hybrid.specialization)
        hybrid.specialization_object = spec
        hybrid.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0002_recoverymail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RunPython(create_empty_specialization),
        migrations.AddField(
            model_name='hybrid',
            name='specialization_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='registration.Specialization'),
        ),
        migrations.RunPython(copy_specialization),
    ]
