# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0003_create_specialization_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybrid',
            name='specialization',
        ),
        migrations.RenameField(
            model_name='hybrid',
            old_name='specialization_object',
            new_name='specialization',
        ),
    ]
