# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0005_specialization_active'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE registration_hybrid SET gender='U' WHERE gender='';"
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='gender',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Dame'), ('U', 'Ukjent')], max_length=1),
        ),
    ]
