# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import apps.registration.models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0006_restrict_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fødselsår'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='gender',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Dame'), ('U', 'Ukjent')], max_length=1,
                                   verbose_name='Kjønn'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='graduation_year',
            field=models.IntegerField(default=apps.registration.models.five_years, verbose_name='Avgangsår'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='image',
            field=models.ImageField(default='placeholder-profile.jpg', upload_to=apps.registration.models.user_folder,
                                    verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='member',
            field=models.BooleanField(default=False, verbose_name='Medlem'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mellomnavn'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT,
                                    to='registration.Specialization', verbose_name='Spesialisering'),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='title',
            field=models.CharField(blank=True, default='Hybrid', max_length=150, verbose_name='Tittel'),
        ),
    ]
