# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0007_add_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='food_preferences',
            field=models.CharField(blank=True, max_length=150, verbose_name='Allergier og matpreferanser'),
        ),
    ]
