# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_hybrid_food_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='card_key',
            field=models.IntegerField(blank=True, null=True, verbose_name='NTNU-kortkode'),
        ),
    ]
