# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0008_hybrid_food_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='gender',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Dame'), ('U', 'Ukjent')], default='U', max_length=1,
                                   verbose_name='Kjønn'),
        ),
    ]
