# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_hybrid_card_key'),
        ('registration', '0009_set_U_as_default_gender'),
    ]

    operations = [
    ]
