# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-10-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20171002_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='card_key',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='NTNU-kortkode'),
        ),
    ]
