# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-10-02 15:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20171002_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='card_key',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='card_key number must contain 10 numbers.', regex='^\\d{10,10}$')], verbose_name='NTNU-kortkode'),
        ),
    ]
