# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:03
from __future__ import unicode_literals

from django.db import migrations

import apps.registration.models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0014_auto_20171102_1324'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hybrid',
            managers=[
                ('objects', apps.registration.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
