# Generated by Django 2.0.2 on 2018-02-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_case_insensitive_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
