# Generated by Django 2.0.4 on 2018-09-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20180206_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybrid',
            name='accepted_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
