# Generated by Django 2.0.8 on 2019-10-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_create_contactperson'),
        ('registration', '0018_auto_20191016_1705'),
    ]

    operations = [
    ]
