# Generated by Django 2.0.8 on 2019-12-06 12:45

from django.db import migrations


def move_data(apps, schema_editor):
    """
    Custom migration operation.
    For each existing subject in hybridopedia,
    it creates a new subject in registration
    and keeps the old data.
    """
    OldSubject = apps.get_model('hybridopedia', 'Subject')
    Subject = apps.get_model('registration', 'Subject')
    for oldSubject in OldSubject.objects.all():
        subject = Subject.objects.create()
        if subject.pk < oldSubject.pk:
            subject.delete()
            subject = Subject.objects.create()
        subject.name = oldSubject.name
        subject.author = oldSubject.author
        subject.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0020_subject'),
        ('hybridopedia', '0003_subject_author'),
    ]

    operations = [
        migrations.RunPython(move_data),
    ]
