# Generated by Django 2.0.8 on 2019-12-06 15:27

from django.db import migrations, models


def split_name_code(apps, schema_editor):
    """
    Custom migration operation.
    For each subject, splits name into subject code and name.
    """
    Subject = apps.get_model('registration', 'Subject')
    for subject in Subject.objects.all():
        subject.code = subject.name.split()[0]
        subject.name = ' '.join(subject.name.split()[2:])
        subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_subject_datamigration'),
        ('hybridopedia', '0004_auto_20191206_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(
                max_length=10,
                unique=True,
                null=True,
                blank=True,
                verbose_name="Fag kode",
            ),
        ),

        migrations.RunPython(split_name_code),

        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(
                max_length=10,
                unique=True,
                null=False,
                blank=False,
                verbose_name="Fag kode",
            ),
        ),

        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="Fag navn",
            ),
        ),

    ]
