# Generated by Django 2.0.8 on 2020-02-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20191206_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='specialization',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Specialization', verbose_name='Spesialisering'),
        ),
    ]
