# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honary_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('awarded', models.CharField(max_length=4)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ridder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('finished', models.CharField(max_length=4)),
                ('awarded', models.CharField(max_length=4)),
                ('description', models.TextField()),
            ],
        ),
    ]
