# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilt_type', models.CharField(max_length=50)),
                ('sporran', models.CharField(max_length=50)),
                ('ekstra', models.CharField(max_length=250)),
                ('annet', models.CharField(max_length=500)),
            ],
        ),
    ]
