# Generated by Django 2.0.4 on 2018-05-18 12:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vevkom', '0004_auto_20180504_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='text',
            field=tinymce.models.HTMLField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='meetingreport',
            name='text',
            field=tinymce.models.HTMLField(max_length=3000),
        ),
    ]
