# Generated by Django 2.0.8 on 2019-10-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vevkom', '0005_auto_20180518_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-status', 'priority']},
        ),
    ]
