# Generated by Django 2.0.8 on 2018-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, choices=[('På lager', 'PÅ lager'), ('Under bestilling', 'Under bestilling'), ('Ikke tilgjengelig', 'Ikke tilgjengelig')], max_length=100),
        ),
    ]
