# Generated by Django 2.0.8 on 2018-11-16 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_auto_20181116_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2018, 11, 16, 22, 28, 5, 203051, tzinfo=utc)),
        ),
    ]
