# Generated by Django 2.0.8 on 2018-11-20 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0008_auto_20181117_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2018, 11, 20, 17, 52, 5, 422774, tzinfo=utc)),
        ),
    ]
