# Generated by Django 2.0.8 on 2018-11-20 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0009_auto_20181120_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('Hentet', 'Hentet'), ('Ikke hentet', 'Ikke hentet')], default='Ikke hentet', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('Betalt', 'Betalt'), ('Ikke betalt', 'Ikke betalt')], default='Ikke betalt', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2018, 11, 20, 18, 4, 10, 829273, tzinfo=utc)),
        ),
    ]
