# Generated by Django 2.0.8 on 2019-01-28 12:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0010_auto_20181120_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2019, 1, 28, 12, 44, 15, 62587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, choices=[('På lager', 'På lager'), ('Under bestilling', 'Under bestilling'), ('Ikke tilgjengelig', 'Ikke tilgjengelig')], max_length=100),
        ),
    ]
