# Generated by Django 2.0.8 on 2019-01-29 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0012_auto_20190129_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontpageImage',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2019, 1, 29, 9, 34, 7, 46049, tzinfo=utc)),
        ),
    ]
