# Generated by Django 2.0.8 on 2019-02-17 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0015_auto_20190129_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
